<a href="https://colab.research.google.com/github/RafsanJany-44/ARC/blob/master/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 01

The dataset contains information of several patients and their corresponding disease. Your task will be to clean this data , visualize it and perform mathematical operation to replace some missing values in the dataset.Please follow the below steps to complete the task:

**(1)** Load the excel data file using pandas dataframe.
**(2)** Print first 10 rows of the dataframe to identify the features.
**(3)** Determine the datatype of the features and whether the data contains any missing values or not (Hint: Print summary of the dataframe).
**(4)** If Symptomps of any patient or patients are missing then drop the entire record of those patients.
**(5)** Print count values of each disease catagory to identify whether the dataset is balanced or not.
**(6)** Create a new dataframe by taking only the Height, Weight and BMI columns of the data
**(7)** Convert the dataframe into numpy array
**(8)** Replace the missing BMI values in the array by using the height and weight of the patients. The formula for BMI is : weight / height^2
**(9)** Replace the BMI column of the previous dataframe with newly obtained values(Hint: Convert the numpy array to a new dataframe giving same column names and replace the BMI column of the old dataframe with the new one)
**(10)** Create a barplot of the patients based on their BMI.(4 catagories for the barplot: Underweight(<18.5), Normal(18.5-24.9), Overweight(25-29.9), Obese(>30)) )  



(1) Load the excel data file using pandas dataframe.

In [2]:
import numpy as np
import pandas as pd

ass_data = pd.read_excel("/content/CSE445_Assignment01.xlsx")

(2) Print first 10 rows of the dataframe to identify the features

In [3]:
ass_data.head(10)

Clinical_text          Disease  \
0  35 years old Masuma Begum is seeing change in ...  Cronh's Disease   
1  Hanif Ahmed at the age of 55 presents to the c...  Cronh's Disease   
2  Apu Sarker is a male of 32 years having fecal ...  Cronh's Disease   
3  Samia Nasreen, a 24 years old female is having...  Cronh's Disease   
4  43 years old Babu Das comes to the clinic for ...  Cronh's Disease   
5  67 years old Abdullah is experiencing change i...  Cronh's Disease   
6  Ridita Haque, a 19 years old female is having ...  Cronh's Disease   
7  Nasir Hasan, a male of 60 years came to the cl...  Cronh's Disease   
8  Hiya Tabassum, 23 years old female is experien...  Cronh's Disease   
9  46 years old Runa Farhana presents to the clin...  Cronh's Disease   

                                            Symptoms  Height (m)  Weight (kg)  \
0                   ['burning sensations', 'sweats']        1.61           80   
1  ['bowel incontinence', 'swelling', 'sweats', '...        1.63           59   
2                  ['fecal incontinence', 'itching']        1.62           60   
3                 ['bleeding', 'swelling', 'sweats']        1.71           53   
4  ['fecal incontinence', 'sweats', 'itching sens...        1.64           69   
5                   ['itching sensations', 'sweats']        1.77           92   
6                            ['itching', 'swelling']        1.69           50   
7       ['bowel incontinence', 'bleeding', 'sweats']        1.72           89   
8                  ['itching', 'swelling', 'sweats']        1.64           74   
9      ['bowel incontinence', 'swelling', 'itching']        1.69           66   

     BMI  
0  30.86  
1  22.21  
2  22.86  
3  18.13  
4  25.65  
5  29.37  
6  17.51  
7  30.08  
8  27.51  
9  23.11

(3) Determine the datatype of the features and whether the data contains any missing values or not (Hint: Print summary of the dataframe).

In [4]:
ass_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359 entries, 0 to 358
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Clinical_text  359 non-null    object 
 1   Disease        359 non-null    object 
 2   Symptoms       354 non-null    object 
 3   Height (m)     359 non-null    float64
 4   Weight (kg)    359 non-null    int64  
 5   BMI            349 non-null    float64
dtypes: float64(2), int64(1), object(3)
memory usage: 17.0+ KB


(4) If Symptomps of any patient or patients are missing then drop the entire record of those patients.

In [5]:
ass_data.dropna(subset = ['Symptoms'], inplace=True)

In [6]:
ass_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 354 entries, 0 to 358
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Clinical_text  354 non-null    object 
 1   Disease        354 non-null    object 
 2   Symptoms       354 non-null    object 
 3   Height (m)     354 non-null    float64
 4   Weight (kg)    354 non-null    int64  
 5   BMI            344 non-null    float64
dtypes: float64(2), int64(1), object(3)
memory usage: 19.4+ KB


(5) Print count values of each disease catagory to identify whether the dataset is balanced or not.

In [7]:
ass_data["Disease"].value_counts()

Depression              60
Hay Fever               55
Parkinson's Disease     50
Stress                  50
Hepatitis B             50
Raynaud's phenomenon    50
Cronh's Disease         39
Name: Disease, dtype: int64

(6) Create a new dataframe by taking only the Height, Weight and BMI columns of the data

In [8]:
new_ass_data = ass_data[["Height (m)","Weight (kg)","BMI"]]

In [9]:
new_ass_data

Height (m)  Weight (kg)    BMI
0          1.61           80  30.86
1          1.63           59  22.21
2          1.62           60  22.86
3          1.71           53  18.13
4          1.64           69  25.65
..          ...          ...    ...
354        1.82           98  29.59
355        1.80           98  30.25
356        1.77           61  19.47
357        1.61           88  33.95
358        1.72           78  26.37

[354 rows x 3 columns]

(7) Convert the dataframe into numpy array

In [12]:
np_data = new_ass_data.to_numpy()

print('\nNumpy Array\n----------\n', np_data)
print('\nNumpy Array Datatype :', np_data.dtype)


Numpy Array
----------
 [[ 1.61 80.   30.86]
 [ 1.63 59.   22.21]
 [ 1.62 60.   22.86]
 ...
 [ 1.77 61.   19.47]
 [ 1.61 88.   33.95]
 [ 1.72 78.   26.37]]

Numpy Array Datatype : float64


(8) Replace the missing BMI values in the array by using the height and weight of the patients. The formula for BMI is : weight / height^2

In [20]:
for i in np_data:
  if str(i[2]) == 'nan':
    print(i)

[ 1.73 86.     nan]
[ 1.65 56.     nan]
[ 1.77 50.     nan]
[ 1.71 80.     nan]
[ 1.79 63.     nan]
[ 1.8 82.   nan]
[ 1.75 43.     nan]
[ 1.63 97.     nan]
[ 1.72 65.     nan]
[ 1.7 59.   nan]


(9) Replace the BMI column of the previous dataframe with newly obtained values(Hint: Convert the numpy array to a new dataframe giving same column names and replace the BMI column of the old dataframe with the new one)

(10) Create a barplot of the patients based on their BMI.(4 catagories for the barplot: Underweight(<18.5), Normal(18.5-24.9), Overweight(25-29.9), Obese(>30)) )